<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<link rel="stylesheet" href="./file_css/footer.css">
<link rel="stylesheet" href="./file_css/prestation.css">
<link rel="stylesheet" href="./file_css/carousel.css">
<link rel="stylesheet" href="./file_css/navbar.css">
<link rel="stylesheet" href="./file_css/apropos.css">
<link rel="stylesheet" href="./file_css/boncadeau.css">
<link rel="stylesheet" href="./file_css/contact.css">
<link rel="stylesheet" href="./file_css/holiday.css">
<link rel="stylesheet" href="./file_css/faq.css">
<link rel="stylesheet" href="./file_css/cgu.css">
<!-- <link rel="stylesheet" href="./file_css/massage_type.css"> -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet">
<style>@import url('https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap');</style>
<link rel="stylesheet" href="./file_css/navbarcgu.css">