<div id="apropos">
    <div id="all">
        <div id="picture">
            <img src="" alt="">
        </div>
        <div id="content">
            <h2>A Propos</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus eaque natus odio quaerat, perferendis, laborum soluta repellendus incidunt assumenda explicabo quis aliquam hic in ipsum eum. Magnam explicabo ea aliquam?</p>
        </div>
    </div>
</div>