<div id="philo">
    <h2>Ma Philosophie</h2>
    <img class="behappymassage" src="./file_assets/virginie.png">
    <div id="philo_content">
        <div id="picture">
            <img class="philo" src="./file_assets/apropos.png" alt="statue de bouddha avec un paysage le tout calme et reposant">
        </div>
        <div id="content">
            <p>Aimer le silence, c’est aimer être en sa propre compagnie pour entendre penser son âme…<br>
                L’énergie vitale maintient le corps en parfait état de santé.<br>
                Son entretien contribue à l’amélioration de la perception de notre bien être et de nos joies.<br>
                <br>
                Je vous offre une boîte à outils avec des techniques différentes qui seront adaptées en fonction de vos maux et de vos émotions.<br>
                <br>
                Prenez le temps pour vous, pour vous détendre et vous relâcher.<br>

                Ensemble trouvons votre soin, votre massage !
            </p>
        </div>
    </div>
</div>