<div id="all">
    <div id="giftform" class="allform">
        <div id="gauche">
            <h2> Bon Cadeau</h2>
            <img src="./file_assets/boncadeau.png" alt="">
        </div>
        <form class="gift">

            <label for="nom">Votre Nom :</label>
            <input type="text" id="nom" name="nom" required>

            <label for="prenom">Votre Prénom :</label>
            <input type="text" id="prenom" name="prenom" required>

            <label for="mail">Votre Mail :</label>
            <input type="email" id="mail" name="mail"required>

            <label for="attention">A l'attention de :</label>
            <input type="text" id="attention" name="attention" required>

            <label for="offertpar">Offert par :</label>
            <input type="text" id="offertpar" name="offertpar"required>

            <p>Prestation, durée ou valeur :</p>

            <label for="prestation">Préstation</label>
            <!-- <input type="text" id="choix" name="choix"required> -->
            <select id="prestation" name="prestation"required>

                <option value="" disabled selected>Choississez la prestation que vous voulez offrir</option>
                <option value="aucun">Je ne souhaite pas offrir de prestation précise.</option>
                <option value="fasciathérapie">La fasciathérapie</option>
                <option value="auriculothérapie">L'auriculothérapie</option>
                <option value="rea">Reset Emotionnel Auriculothérapie REA</option>
                <option value="ventouses">Ventouses</option>
                <option value="dos-tensions">Massage dos et tensions musculaires</option>
                <option value="children">Massage enfant et bébé</option>
                <option value="reflexologie">Réflexologie plantaire</option>
                <option value="massage">Les massages</option>
                <option value="ventre">Massage ventre Tuina</option>
                <option value="moxibustion">La Moxibustion</option>
                <option value="enceinte">Massage femme enceinte</option>
                <option value="kobido">Massage Japonais du visage dit "Kobido"</option>
                <option value="lampe">La lampe Wai Qi</option>
                <option value="pressothérapie">La Pressothérapie</option>

            </select>

            <label for="duree">Durée</label>
            <select id="duree" name="duree"required>

                <option value=""disabled selected>Choississez la durée que vous voulez offrir</option>
                <option value="aucune">Je ne souhaite pas offrir une durée</option>
                <option value="trente">30 minutes</option>
                <option value="soixante">60 minutes</option>
                <option value="quatre-vingt-dix">90 minutes</option>
                <option value="cent-vingt">120 minutes</option>

            </select>

            <label for="valeur">Valeur</label>
            <input type="number" id="valeur" name="valeur"required>

            <label for="reception">Préciser si vous voulez recevoir le bon cadeau par mail ou si vous voulez le retirer directement au salon Be Happy Massage</label>
            <input type="text" id="reception" name="reception"required>

            <label for="reglement">Virement, Espèces ou Chèque :</label>
            <input type="text" id="reglement" class="last" name="reglement"required>

            <div id="check">

                <input type="checkbox" id="checkbox" name="checkboxboncadeau" required>
                <label for="checkbox">Je confirme les informations renseignées</label>
            
            </div>

            <input type="submit" value="Envoyer" class="submit-btn">

        </form>
    </div>
</div>