
<div id="carousel">
    <!-- <div id="carouselExampleSlidesOnly" class="carousel slide carousel-fade" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="./file_assets/slide1.png" class="d-block w-100 image" alt="...">
            </div>
            <div class="carousel-item">
                <img src="./file_assets/slide2.png" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="./file_assets/slide3.png" class="d-block w-100" alt="...">
            </div>
        </div>
    </div> -->
    <div class="centre-item">
        <img src="./file_assets/slide2.png" class="image" alt="...">
    </div>



</div>
