<div id="contact">
    <div id="contact_infos" class="informations">
        <div id="gauche_contact">
            <h2> Contact</h2>
        </div>
        <div id="droite_contact">
        <form class="contactme">

            <label for="nom">Votre Nom :</label>
            <input type="text" id="contact_nom" name="nom" required>

            <label for="prenom">Votre Prénom :</label>
            <input type="text" id="contact_prenom" name="prenom" required>

            <label for="mail">Votre Mail :</label>
            <input type="email" id="contact_mail" name="mail"required>

            <label for="message">Votre message concerne :</label>
            <input type="text" id="raison" class="raison" name="reglement"required>

            <label for="contenu">Tapez votre message ici</label>
            <input type="text" id="message" class="message" name="message"required>

            <div id="check">

                <input type="checkbox" id="checkbox" name="checkboxboncadeau" required>
                <label for="checkbox">Je confirme les informations renseignées</label>
            
            </div>

            <input type="submit" value="Envoyer" class="contact-submit-btn">

        </form>
        </div>
    </div>
</div>