<div id="informations">
    <h2> Contact</h2>
    <div id="contact">
        <div id="gauche_contact">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2764.3396504999096!2d5.797357684484758!3d46.14398230746819!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x478c9b5c21fbde83%3A0xf52ddf9f06c52acb!2s671%20Rue%20Aim%C3%A9%20Bonneville%2C%2001200%20Valserh%C3%B4ne!5e0!3m2!1sfr!2sfr!4v1721658564483!5m2!1sfr!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        <div id="contact_infos" class="informations">
            <div id="droite_contact">
            <form class="contactme">

                <label for="nom">Votre Nom :</label>
                <input type="text" id="contact_nom" name="nom" required>

                <label for="prenom">Votre Prénom :</label>
                <input type="text" id="contact_prenom" name="prenom" required>

                <label for="mail">Votre Mail :</label>
                <input type="email" id="contact_mail" name="mail"required>

                <label for="message">Votre message concerne :</label>
                <input type="text" id="raison" class="raison" name="reglement"required>

                <label for="contenu">Tapez votre message ici</label>
                <input type="text" id="message" class="message" name="message"required>

                <div id="check">

                    <input type="checkbox" id="checkbox" name="checkboxboncadeau" required>
                    <label for="checkbox">Je confirme les informations renseignées</label>
                
                </div>

                <input type="submit" value="Envoyer" class="contact-submit-btn">

            </form>
            </div>
        </div>
    </div>
</div>