<div id="informations">
    <h2> Contact</h2>
    <div id="contact">
        <div id="gauche_contact">
                <p>671 Rue Aimé Bonneville 01200 Valserhône</p>
                <svg class="wheel" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-wheelchair" viewBox="0 0 16 16"><path d="M12 3a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3m-.663 2.146a1.5 1.5 0 0 0-.47-2.115l-2.5-1.508a1.5 1.5 0 0 0-1.676.086l-2.329 1.75a.866.866 0 0 0 1.051 1.375L7.361 3.37l.922.71-2.038 2.445A4.73 4.73 0 0 0 2.628 7.67l1.064 1.065a3.25 3.25 0 0 1 4.574 4.574l1.064 1.063a4.73 4.73 0 0 0 1.09-3.998l1.043-.292-.187 2.991a.872.872 0 1 0 1.741.098l.206-4.121A1 1 0 0 0 12.224 8h-2.79zM3.023 9.48a3.25 3.25 0 0 0 4.496 4.496l1.077 1.077a4.75 4.75 0 0 1-6.65-6.65z"/></svg>
                <p>Accès handicapé</p>
                <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd"><path d="M8.26 1.289l-1.564.772c-5.793 3.02 2.798 20.944 9.31 20.944.46 0 .904-.094 1.317-.284l1.542-.755-2.898-5.594-1.54.754c-.181.087-.384.134-.597.134-2.561 0-6.841-8.204-4.241-9.596l1.546-.763-2.875-5.612zm7.746 22.711c-5.68 0-12.221-11.114-12.221-17.832 0-2.419.833-4.146 2.457-4.992l2.382-1.176 3.857 7.347-2.437 1.201c-1.439.772 2.409 8.424 3.956 7.68l2.399-1.179 3.816 7.36s-2.36 1.162-2.476 1.215c-.547.251-1.129.376-1.733.376"/></svg>
                <a href="tel:+33601854903" class="phonenumber">06 01 85 49 03</a>
                <a class="facebook" href="https://www.facebook.com/people/Be-Happy-Massage/100085586681605/"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm3 8h-1.35c-.538 0-.65.221-.65.778v1.222h2l-.209 2h-1.791v7h-3v-7h-2v-2h2v-2.308c0-1.769.931-2.692 3.029-2.692h1.971v3z"/></svg></a>
                <a class="facebook-button" href="https://www.facebook.com/people/Be-Happy-Massage/100085586681605/" target="_blank">
                <button type="button">Visitez mon Facebook</button>
                </a>
                <div class="horaires">
                    <h4>Horaires d'ouverture</h4>
                    <ul>
                        <li class="ferme">Dimanche : Fermé</li>
                        <li class="ferme">Lundi : Fermé</li>
                        <li class="ouvert">Mardi : 9h30 - 19h00</li>
                        <li class="ouvert">Mercredi : 9h30 - 19h00</li>
                        <li class="ferme">Jeudi : Fermé</li>
                        <li class="ouvert">Vendredi : 9h30 - 19h00</li>
                        <li class="ouvert">Samedi : 9h30 - 17h00</li>
                    </ul>
                </div>
                <div class="iframe">
                    <iframe class="first" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2764.3396504999096!2d5.797357684484758!3d46.14398230746819!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x478c9b5c21fbde83%3A0xf52ddf9f06c52acb!2s671%20Rue%20Aim%C3%A9%20Bonneville%2C%2001200%20Valserh%C3%B4ne!5e0!3m2!1sfr!2sfr!4v1721658564483!5m2!1sfr!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe><br>
                    <iframe class="second" src="https://www.google.com/maps/embed?pb=!4v1730398938620!6m8!1m7!1sCFPykLA1bzh1dYfKFUuwJQ!2m2!1d46.14383443047382!2d5.798669354248467!3f285.5863947648687!4f-7.236235576990936!5f0.4000000000000002" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
                </div>
        <div id="contact_infos" class="informations">
            <div id="droite_contact">
            <form class="contactme" action="https://formspree.io/f/mnnawkdy" method="POST">

                <label for="nom">Votre Nom :</label>
                <input type="text" class="contactme-input" name="nom" required>

                <label for="prenom">Votre Prénom :</label>
                <input type="text" class="contactme-input" name="prenom" required>

                <label for="mail">Votre Mail :</label>
                <input type="email" class="contactme-input" name="mail" required>

                <label for="telephone">Votre Numéro de Téléphone :</label>
                <input type="tel" class="contactme-input" id="phone" name="phone" required>

                <label for="message">Votre message concerne :</label>
                <input type="text" class="contactme-input" name="sujet" required>

                <label for="contenu">Tapez votre message ici :</label>
                <textarea id="message" class="contactme-input" name="message" required></textarea>

                <div id="check">

                    <input type="checkbox" id="checkbox" name="checkboxboncadeau" required>
                    <label for="checkbox">Je confirme que les informations renseignées soient conservées par Be Happy Massage afin de me contacter.</label>
                
                </div>

                <input type="submit" value="Envoyer" class="contact-submit-btn contactme-input">
                
            </form>
            </div>
        </div>
    </div>
</div>