<div id="faq">
    <h2> FAQ </h2>
    <div class="accordion" id="accordionExample">
        <div class="accordion-item"> <!-- Question 1 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                A qui s'adresse les massages ?
            </button>
            </h3>
            <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Les massages s’adressent à tous, petits et grands, tout ceux qui souhaitent se détendre, les sportifs, les personnes avec de douleurs musculaires, tendineux, les problèmes de sommeil, problèmes digestifs, les personnes angoissées, stressées…
            </div>
            </div>
        </div>
        <div class="accordion-item"><!-- Question 2 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Est-ce qu’il y a des contre indications pour se faire masser ou recevoir un soin ?
            </button>
            </h3>
            <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Oui car un massage ou un soin ne sont pas anodins car nous agissons sur l’organisme et en fonction de votre état général, vos douleurs ou pathologies.

                Il est préférable de me contacter pour plus d’informations.
            </div>
        </div>
        <div class="accordion-item"> <!-- Question 3 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                J’ai des difficultés à tourner la tête, mes cervicales sont tendues, que pouvez-vous faire ?
            </button>
            </h3>
            <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                En connaître l’origine aiderait à orienter les soins ou massages adaptés, ensuite la fasciathérapie, l’auriculothérapie, la reflexologie et le massage seront vous apporter de la détente, nous verrons le jour du rendez-vous.
            </div>
            </div>
        </div>
        <div class="accordion-item"><!-- Question 4 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                J’ai une tendinite, puis-je me faire masser ?
            </button>
            </h3>
            <div id="collapseFour" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Oui il est possible de recevoir un massage ou un soin, nous travaillerons sur l’ensemble de votre corps qui lui permettra ensuite de relâcher les zones de tensions ainsi améliorer votre tendinite.
            </div>
            </div>
        </div>
        <div class="accordion-item"><!-- Question 5 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                Je suis stressé, angoissé avec des troubles du sommeil, que pouvez-vous faire ?
            </button>
            </h3>
            <div id="collapseFive" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Plusieurs outils permettront d’améliorer votre état général, l’auriculothérapie en émotionnel par exemple, mais aussi le massage du ventre, un massage adapté…
            </div>
            </div>
        </div>
        <div class="accordion-item"><!-- Question 6 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
                Avez-vous un massage pour soulager les migraines ?
            </button>
            </h3>
            <div id="collapseSix" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Le shiatsu est une approche intéressante mais aussi la fasciathérapie, l’auriculothérapie.
            </div>
            </div>
        </div>
        <div class="accordion-item"><!-- Question 7 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
                Je suis émuisée, manque d'énergie, pouvez-vous me proposer un massage ?
            </button>
            </h3>
            <div id="collapseSeven" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Lorsque nous sommes fatigués, notre énergie vitale est bloquée et ne peut circuler dans notre corps. La moxibustion est une technique thérapeutique et débloquera votre énergie en éliminant le stress.
            </div>
            </div>
        </div>
        <div class="accordion-item"><!-- Question 8 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
                Des problèmes digestifs, que proposez-vous ?
            </button>
            </h3>
            <div id="collapseEight" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Les problèmes digestifs sont nombreux, en connaître la cause est avant tout une priorité, étudier ensemble votre mode de vie, votre état de stress... Le massage du ventre sera un atout pour ces soucis digestifs, tensions musculaires en sont souvent la cause. 
            </div>
            </div>
        </div>
        <div class="accordion-item"><!-- Question 9 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseNine" aria-expanded="false" aria-controls="collapseNine">
                Avez-vous un massage pour les douleurs lombaires sensation de "barre dans le dos" ? 
            </button>
            </h3>
            <div id="collapseNine" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Le dos appelé l'arbre de la vie est l'endroit où nous retrouvons toutes nos émotions. Des postures répétées sont souvent aussi responsables de ces douleurs, un massage profond du dos vous permettra de soulager toutes ces parties et retrouver ainsi une sensation de détente.
            </div>
            </div>
        </div>

    </div>
</div>