<div id="faq">
    <h2> FAQ </h2>
    <div class="accordion" id="accordionExample">
        <div class="accordion-item"> <!-- Question 1 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                A qui s'adresse les massages ?
            </button>
            </h3>
            <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Les massages sont accessibles à tous, tout ceux qui souhaitent se détendre, aux sportifs, aux troubles digestifs, douleurs musculaires ...
            </div>
            </div>
        </div>
        <div class="accordion-item"><!-- Question 2 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Y a t'il des contre-indications ?
            </button>
            </h3>
            <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Oui car se faire masser n'est pas anodin. Les contre-indications : cancer, fractures, femmes enceintes, diabête type II ... Pour plus d'informations, je vous invite à me contacter.
            </div>
        </div>
        <div class="accordion-item"> <!-- Question 3 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Est-ce qu'il est possible de se faire masser avec une tenidite au bras ?
            </button>
            </h3>
            <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Oui je peux proposer diffèrents massages, des techniques diffèrentes pour soulager la douleur. Et ensuite un bon repos.
            </div>
            </div>
        </div>
        <div class="accordion-item"><!-- Question 4 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                Avez-vous un massage pour soulager les migraines ?
            </button>
            </h3>
            <div id="collapseFour" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Oui l'approche du shiatsu est intéressante pour les migraines. Les points exercés permettront de libérer la pression crânienne.
            </div>
            </div>
        </div>
        <div class="accordion-item"><!-- Question 5 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                Avez-vous des solutions pour les troubles de sommeil ?
            </button>
            </h3>
            <div id="collapseFive" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Les troubles du sommeil restent multiples, il est important d'en connaitre l'origine. Diverses techniques alliées à la détente permettront au corps de se relâcher. La réflexologie plantaire est une approche utilisée pour ces troubles.
            </div>
            </div>
        </div>
        <div class="accordion-item"><!-- Question 6 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
                J'ai des difficultés à tourner la tête, j'ai mal aux cervicales, pouvez-vous me soulager ?
            </button>
            </h3>
            <div id="collapseSix" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Les douleurs que vous avez aux cervicales sont la pupart du temps lées aux tensions musculaires. Lors de la séance, je chercherai l'origine des ces douleurs avec un massage profond du dos pour vous libérer de toutes ces tensions.
            </div>
            </div>
        </div>
        <div class="accordion-item"><!-- Question 7 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
                Je suis émuisée, manque d'énergie, pouvez-vous me proposer un massage ?
            </button>
            </h3>
            <div id="collapseSeven" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Lorsque nous sommes fatigués, notre énergie vitale est bloquée et ne peut circuler dans notre corps. La moxibustion est une technique thérapeutique et débloquera votre énergie en éliminant le stress.
            </div>
            </div>
        </div>
        <div class="accordion-item"><!-- Question 8 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
                Des problèmes digestifs, que proposez-vous ?
            </button>
            </h3>
            <div id="collapseEight" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Les problèmes digestifs sont nombreux, en connaître la cause est avant tout une priorité, étudier ensemble votre mode de vie, votre état de stress... Le massage du ventre sera un atout pour ces soucis digestifs, tensions musculaires en sont souvent la cause. 
            </div>
            </div>
        </div>
        <div class="accordion-item"><!-- Question 9 -->
            <h3 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseNine" aria-expanded="false" aria-controls="collapseNine">
                Avez-vous un massage pour les douleurs lombaires sensation de "barre dans le dos" ? 
            </button>
            </h3>
            <div id="collapseNine" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Le dos appelé l'arbre de la vie est l'endroit où nous retrouvons toutes nos émotions. Des postures répétées sont souvent aussi responsables de ces douleurs, un massage profond du dos vous permettra de soulager toutes ces parties et retrouver ainsi une sensation de détente.
            </div>
            </div>
        </div>

    </div>
</div>