    <div class="footer-section">
        <div class="container">
            <div class="footer-cta pt-5 pb-5">
                <div class="row">
                    <div class="col-xl-6 col-md-6 mb-30">
                        <div class="single-cta">
                            <div class="cta-text">
                                <h4>Me trouver</h4>
                                <span>671 Rue Aimé Bonneville 01200 Valserhône</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6 col-md-6 mb-30">
                        <div class="single-cta">
                            <div class="cta-text">
                                <h4>Me contacter</h4>
                                <span>06 01 85 49 03</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-content pt-5 pb-5">
                <div class="row">
                    <div class="col-xl-6 col-lg-6 mb-50">
                        <div class="footer-widget">
                            <div class="footer-logo">
                                <h4>Be Happy Massage</h4>
                            </div>
                            <div class="footer-text">
                                <p>Venez trouver mon cabinet à Chatillon en michaille au sein du pôle culturel à 5 min de Bellegarde sur Valserine.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 mb-50">
                        <div class="footer-widget">
                            <div class="footer-widget-heading">
                                <h3>Liens Utiles</h3>
                            </div>
                            <ul>
                                <li><a href="#philo">Ma Philosophie</a></li>
                                <li><a href="#allprestations">Mes Prestations</a></li>
                                <li><a href="#informations">Contact</a></li>
                                <li><a href="#faq">FAQ</a></li>
                                <li><a href="#giftform">Bon Cadeau</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright-area">
            <div class="container">
                <div class="row testing">
                    <div class="col-xl-6 col-lg-6 text-center text-lg-left">
                        <div class="copyright-text">
                            <p>Copyright &copy; 2024 All Rights Reserved by Be Happy Massage.</a></p>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 text-right">
                        <div class="footer-menu">
                            <ul>
                                <li><a href="cgu.php">CGU</a></li>
                                <li><a href="cgu.php">Politique de Confidentialité</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>