<footer class="site-footer">
        <div class="container">
            <div class="row">
            <div class="col-sm-12 col-md-6">
                <h6>A propos</h6>
                <p class="text-justify">Venez trouver mon cabinet à Chatillon en michaille au sein du pôle culturel à 5 min de Bellegarde sur Valserine.</p>
            </div>

            <div class="col-xs-6 col-md-3">
                <h6>Liens rapides</h6>
                <ul class="footer-links">
                    <li class="nav-item basic">
                        <a class="nav-link active" aria-current="page" href="#philo">Ma philosophie</a>
                    </li>
                    <li class="nav-item basic">
                        <a class="nav-link" href="#allprestations">Prestations</a>
                    </li>
                    <li class="nav-item basic">
                        <a class="nav-link" href="#informations">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link prio" href="#giftform">Bon Cadeau</a>
                    </li>
                    <li class="nav-item basic">
                        <a class="nav-link" href="#faq">FAQ</a>
                    </li>
                </ul>
            </div>
            </div>
            <hr>
        </div>
        <div class="container">
            <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
                <p class="copyright-text">Copyright &copy; 2024 All Rights Reserved by Be Happy Massage.</p>
            </div>

            <div class="col-md-4 col-sm-6 col-xs-12">
                <ul class="social-icons">
                <li><a class="facebook" href="https://www.facebook.com/people/Be-Happy-Massage/100085586681605/"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm3 8h-1.35c-.538 0-.65.221-.65.778v1.222h2l-.209 2h-1.791v7h-3v-7h-2v-2h2v-2.308c0-1.769.931-2.692 3.029-2.692h1.971v3z"/></svg></a></li> 
                </ul>
            </div>
            </div>
        </div>
</footer>