<section id="holiday">

    <div id="all_content_holiday">

        <h2 id="holiday_annonce"><i>Actuellement en formation,<br>
                                    retour le mercredi 29 janvier 2025.</i><br>
                                <i>Je reste joignable pour les rendez-vous et bons cadeaux.</i>
    </h2>

        <!-- <div id="holiday_title">
            <h2>Les horaires changent pendant les fêtes à partir du 17 décembre 2024.<br>
            <i>(permanence pour la vente des Bons Cadeau)</i></h2>
        </div>
        <div id="horaires_holiday">
                <ul>
                    <li>Mardi 17 Décembre 2024 de 9h30 à 19h30</li><br>
                    <li>Mercredi 18 Décembre 2024 de 9h00 à 19h00</li><br>
                    <li>Jeudi 19 Décembre 2024 de 9h00 à 19h00</li><br>
                    <li>Vendredi 20 Décembre 2024 de 9h00 à 19h00</li><br>
                    <li>Samedi 21 Décembre 2024 de 9h00 à 18h00</li><br>
                    <li>Dimanche 22 Décembre 2024 de 9h00 à 13h00</li><br>
                    <li>Lundi 23 Décembre 2024 de 9h30 à 19h30</li><br>
                    <li>Mardi 24 Décembre 2024 de 9h00 à 17h30</li>
                </ul>
        </div> -->
        <div id="picture_holiday">
            <img class="holiday" src="./file_assets/formation.jpg" alt="plusieurs cadeaux pour la période de fêtes de fin d'année">
        </div>

    </div>

</section>