<section id="massage_type">
    <h2 id="massage_type_title">Choisissez le massage qui vous convient !</h2>

    <div id="section_container">
        <div id="section_left">
            <img class="massage_picture" src="./file_assets/aura.jpg" alt="personne avec une aura et plusieurs énergies en elle et autour"> 
            <a class="massage_choice" href="#">Envie d'énergie ?</a>
        </div>

        <div id="section_droite">
            <img class="massage_picture" src="./file_assets/meditation.jpg" alt="personne qui se relaxe et médite seule au milieu d'un champ">
            <a class="massage_choice" href="#">Envie de détente ?</a>
        </div>
    </div>
</section>
