<div id="entreprise">
    <h1>Be Happy Massage</h1>
    <nav>
        <ul class="nav justify-content-center">
            <li class="nav-item basic">
                <a class="nav-link active" aria-current="page" href="#">A Propos</a>
            </li>
            <li class="nav-item basic">
                <a class="nav-link" href="#allprestations">Prestations</a>
            </li>
            <li class="nav-item basic">
                <a class="nav-link" href="#informations">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link prio" href="#giftform">Bon Cadeau</a>
            </li>
        </ul>
    </nav>
</div>