
<nav id="entreprise-cgu" class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <h1>Be Happy Massage</h1>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item basic">
                            <a class="nav-link" aria-current="page" href="index.php">Accueil</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>