<div id="entreprise">
    <h1>Be Happy Massage</h1>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button> -->
            <!-- <div class="collapse navbar-collapse" id="navbarTogglerDemo01"> -->
            <ul class="nav justify-content-center .navbar-expand">
                    <li class="nav-item basic">
                        <a class="nav-link" href="#philo">Ma Philosophie</a>
                    </li>
                    <li class="nav-item basic">
                        <a class="nav-link" href="#allprestations">Prestations</a>
                    </li>
                    <li class="nav-item basic">
                        <a class="nav-link" href="#informations">Contact</a>
                    </li>
                    <li class="nav-item basic">
                        <a class="nav-link" href="#faq">FAQ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link prio" href="#giftform">Bon Cadeau</a>
                    </li>
                </ul>
            <!-- </div> -->
        </div>
    </nav>

    <!-- <h1>Be Happy Massage</h1>
    <nav>
        <ul class="nav justify-content-center .navbar-expand">
            <li class="nav-item basic">
                <a class="nav-link active" aria-current="page" href="#philo">Ma Philosophie</a>
            </li>
            <li class="nav-item basic">
                <a class="nav-link" href="#allprestations">Prestations</a>
            </li>
            <li class="nav-item basic">
                <a class="nav-link" href="#informations">Contact</a>
            </li>
            <li class="nav-item basic">
                <a class="nav-link" href="#faq">FAQ</a>
            </li>
            <li class="nav-item">
                <a class="nav-link prio" href="#giftform">Bon Cadeau</a>
            </li>
        </ul>
    </nav> -->
</div>

