<div id="allprestation">
    <h2>Préstations</h2>
        <div id="prestation">
            <div class="wrapper">
                <div class="ligne">
                    <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <img id="oreille" src="./file_assets/fascia.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p>
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                    </div>
                    <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <img id="oreille" src="./file_assets/auriculotherapie.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p>
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                    </div>
                    <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <img id="oreille" src="./file_assets/rea.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p>
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                    </div>
                </div>
                <div class="ligne">
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <img id="oreille" src="./file_assets/ventouse.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p>
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <img id="oreille" src="./file_assets/dos.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p>
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <img id="oreille" src="./file_assets/enfant.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p>
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="ligne">
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <img id="oreille" src="./file_assets/reflexologie.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p>
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <img id="oreille" src="./file_assets/massage.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p>
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <img id="oreille" src="./file_assets/ventre.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p>
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="ligne">
                    <div class="container-all">
                        <div class="card-container">
                            <div class="card1">
                                <div class="img-content">
                                    <img id="oreille" src="./file_assets/moxibustion.png" id="massage" alt="">
                                </div>
                                <div class="content">
                                    <p class="heading">Card Hover</p>
                                    <p>
                                    Lorem ipsum dolor sit amet, consectetur adipii
                                    voluptas ten mollitia pariatur odit, ab
                                    minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                    necessitatibus dignissimos molestias.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="container-all">
                        <div class="card-container">
                            <div class="card1">
                                <div class="img-content">
                                    <img id="oreille" src="./file_assets/femme_enceinte.png" id="massage" alt="">
                                </div>
                                <div class="content">
                                    <p class="heading">Card Hover</p>
                                    <p>
                                    Lorem ipsum dolor sit amet, consectetur adipii
                                    voluptas ten mollitia pariatur odit, ab
                                    minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                    necessitatibus dignissimos molestias.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="container-all">
                        <div class="card-container">
                            <div class="card1">
                                <div class="img-content">
                                    <img id="oreille" src="./file_assets/visage.png" id="massage" alt="">
                                </div>
                                <div class="content">
                                    <p class="heading">Card Hover</p>
                                    <p>
                                    Lorem ipsum dolor sit amet, consectetur adipii
                                    voluptas ten mollitia pariatur odit, ab
                                    minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                    necessitatibus dignissimos molestias.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ligne">
                    <div class="container-all">
                        <div class="card-container">
                            <div class="card1">
                                <div class="img-content">
                                    <img id="oreille" src="./file_assets/lampe.png" id="massage" alt="">
                                </div>
                                <div class="content">
                                    <p class="heading">Card Hover</p>
                                    <p>
                                    Lorem ipsum dolor sit amet, consectetur adipii
                                    voluptas ten mollitia pariatur odit, ab
                                    minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                    necessitatibus dignissimos molestias.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="container-all">
                    <div class="card-container">
                        <div class="card1">
                            <div class="img-content">
                                <img id="oreille" src="./file_assets/pressotherapie.png" id="massage" alt="">
                            </div>
                            <div class="content">
                                <p class="heading">Card Hover</p>
                                <p>
                                Lorem ipsum dolor sit amet, consectetur adipii
                                voluptas ten mollitia pariatur odit, ab
                                minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                necessitatibus dignissimos molestias.
                                </p>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
</div>
