<div id="allprestations">
    <h2> Prestations</h2>
        <div id="presta">
            <div class="wrapper">
                <div class="ligne">
                    <div class="prestation"><!-- Fascia -->
                        <img src="./file_assets/fascia.png" id="fascia">
                        <div class="product">
                            <span class="product-name">La fasciathérapie</span>
                        </div>
                        <div class="description">
                            <p>Séance qui aura pour but de soulager le corps de toutes les tensions quotidiennes accumulées, les mauvaises postures, le stress du système digestif occasionnant des "noeuds".</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <!-- <button class="info-button">Plus d'informations</button> -->
                        </div>
                    </div>
                    <div class="prestation"><!-- L'auriculothérapie -->
                        <img src="./file_assets/auriculotherapie.png" id="auriculo">
                        <div class="product">
                            <span class="product-name">L'auriculothérapie</span>
                        </div>
                        <div class="description">
                            <p>L'oreille est le reflet de notre état général. Au même titre que la réflexologie, l'auriculothérapie vous rééquilibrera, une méthode douce où nous utiliserons diverses méthodes pour palier aux maux rencontrés.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <!-- <button class="info-button">Plus d'informations</button> -->
                        </div>
                    </div>
                    <div class="prestation"><!-- Reset Emotionnel Auriculothérapie REA -->
                        <img src="./file_assets/REA.png" id="REA">
                        <div class="product">
                            <span class="product-name">Reset Emotionnel Auriculothérapie REA</span>
                        </div>
                        <div class="description">
                            <p>C'est une méthode de l'auriculothérapie visant à supprimer les émotions excessives.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <!-- <button class="info-button">Plus d'informations</button> -->
                        </div>
                    </div>
                </div>
                <div class="ligne">
                    <div class="prestation"><!-- Ventouses -->
                        <img src="./file_assets/ventouse.png" id="ventouse">
                        <div class="product">
                            <span class="product-name">Ventouses</span>
                        </div>
                        <div class="description">
                            <p>Les ventouses sont une aide précieuse pour les maux du quotidien (grippe, rhume, arthrite, dépression, sciatique, anxiété, les problèmes intestinaux, les douleurs musculaires, la cellulite ...).</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <!-- <button class="info-button">Plus d'informations</button> -->
                        </div>
                    </div>
                    <div class="prestation"><!-- Massage dos et tensions musculaires -->
                        <img src="./file_assets/dos.png" id="dos">
                        <div class="product">
                            <span class="product-name">Massage dos et tensions musculaires</span>
                        </div>
                        <div class="description">
                            <p>Le massage permet aux muscies de se détendre, sensation de libération, soulagera les douleurs cervicales, trapèzes, dorsales et lombaires, les jambes plus légères. </p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <!-- <button class="info-button">Plus d'informations</button> -->
                        </div>
                    </div>
                    <div class="prestation"><!-- Massage enfant et bébé -->
                        <img src="./file_assets/enfant.png" id="bebe">
                        <div class="product">
                            <span class="product-name">Massage enfant et bébé</span>
                        </div>
                        <div class="description">
                            <p>Être à l'écoute de votre enfant, de votre bébé, nous entendrons leurs maux, nous passerons le temps nécessaire ensemble pour adapter leur massage.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <!-- <button class="info-button">Plus d'informations</button> -->
                        </div>
                    </div>
                </div>
                <div class="ligne">
                    <div class="prestation"><!-- Réflexologie plantaire -->
                        <img src="./file_assets/reflexologie.png" id="plantaire">
                        <div class="product">
                            <span class="product-name">Réflexologie plantaire</span>
                        </div>
                        <div class="description">
                            <p>La réflexologie plantaire chinoise est destinée à apaiser les tensions et l'équilibre énergétique de notre corps.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <!-- <button class="info-button">Plus d'informations</button> -->
                        </div>
                    </div>
                    <div class="prestation"><!-- Les massages personnalisés -->
                        <img src="./file_assets/massage.png" id="perso">
                        <div class="product">
                            <span class="product-name">Les massages personnalisés</span>
                        </div>
                        <div class="description">
                            <p>Vous êtes unique, c'est pour cela que je propose un massage adapté à vos besoins, ensemble nous trouverons votre massage.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <!-- <button class="info-button">Plus d'informations</button> -->
                        </div>
                    </div>
                    <div class="prestation"><!-- Massage ventre Tuina -->
                        <img src="./file_assets/ventre.png" id="ventre">
                        <div class="product">
                            <span class="product-name">Massage ventre Tuina</span>
                        </div>
                        <div class="description">
                            <p>C'est un massage issu de la Médecine traditionnelle chinoise. Si vous êtes tendus, vous avez des problèmes digestifs, il vous apportera une réelle détente.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <!-- <button class="info-button">Plus d'informations</button> -->
                        </div>
                    </div>
                </div>
                <div class="ligne">
                    <div class="prestation"><!-- La Moxibustion -->
                        <img src="./file_assets/moxibustion.png" id="moxi">
                        <div class="product">
                            <span class="product-name">La Moxibustion</span>
                        </div>
                        <div class="description">
                            <p>La Moxibustion consiste à stimuler avec de la chaleur armoise, des points d'acupuncture et certaines autres parties déterminées du corps humain.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <!-- <button class="info-button">Plus d'informations</button> -->
                        </div>
                    </div>
                    <div class="prestation"><!-- Massage femme enceinte -->
                        <img src="./file_assets/femme_enceinte.png" id="enceinte">
                        <div class="product">
                            <span class="product-name">Massage femme enceinte</span>
                        </div>
                        <div class="description">
                            <p>Venez vous faire chouchouter avec un massage de relaxation adapté à vos besoins. Moment de détente pour bébé et vous !</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <!-- <button class="info-button">Plus d'informations</button> -->
                        </div>
                    </div>
                    <div class="prestation"><!-- Massage Japonais du visage dit "Kobido" -->
                        <img src="./file_assets/visage.png" id="visage">
                        <div class="product">
                            <span class="product-name">Massage Japonais du visage dit "Kobido"</span>
                        </div>
                        <div class="description">
                            <p>Ce massage facial intervient sur les méridiens et leurs points énergétiques de façon à libérer les tensions et à participer au rééquilibrage énergétique.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <!-- <button class="info-button">Plus d'informations</button> -->
                        </div>
                    </div>
                </div>
                <div class="ligne">
                    <div class="prestation"><!-- La lampe Wai Qi -->
                        <img src="./file_assets/lampe.png" id="lampe">
                        <div class="product">
                            <span class="product-name">La lampe Wai Qi</span>
                        </div>
                        <div class="description">
                            <p>Apporter une réponse adaptée aux problèmes articulaires, tendineux. Chasse la fatigue, renforce l'immunité et le système digestif. Soulage les affections respirations et les diffèrents maux du corps.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <!-- <button class="info-button">Plus d'informations</button> -->
                        </div>
                    </div>
                    <div class="prestation"><!-- La Pressothérapie -->
                        <img src="./file_assets/pressotherapie.png" id="presso">
                        <div class="product">
                            <span class="product-name">La Pressothérapie</span>
                        </div>
                        <div class="description">
                            <p>La préssothérapie est une méthode qui améliore la circulation sanguine et lymphatique, favorise l'élimination des toxines, aide le retour veineux , sensation de légèreté durables. </p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <!-- <button class="info-button">Plus d'informations</button> -->
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>