<div id="allprestation">
    <h2>Préstations</h2>
        <div id="prestation">
            <div class="wrapper">
                <div class="ligne">
                    <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    
                                    <div class="img-content">
                                        <h3 class="card-title">La fasciathérapie</h3>
                                        <p class="details">30 à 45 min : 60 €</p>
                                        <img id="oreille" src="./file_assets/fascia.png" id="massage" alt="">
                                        
                                    </div>
                                    <div class="content">
                                        <!-- <p class="heading">Card Hover</p> -->
                                        <p class="texte">
                                        Séance qui aura pour but de soulager le corps de toutes les tensions quotidiennes accumulées, 
                                        les mauvaises postures, le stress du système digestif occasionnant des "noeuds", 
                                        nous travaillerons également sur le système nerveux autonome, un rééquilibrage de l'organisme. 
                                        La personne peut rester habillée (vêtements coton près du corps).
                                        </p>
                                    </div>
                                </div>
                            </div>
                    </div>
                    <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <h3 class="card-title">L'auriculothérapie</h3>
                                        <p class="details">30 à 45 min : 60 €</p>
                                        <img id="oreille" src="./file_assets/auriculotherapie.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <!-- <p class="heading">Card Hover</p> -->
                                        <p class="texte-grand">
                                        Et si on s'occupait de vos oreilles ! L'oreille est le reflet de notre état général, 
                                        le saviez-vous ? Au même titre que la réflexologie, l'auriculothérapie vous rééquilibrera, 
                                        une méthode douce (sans aiguille) où nous utiliserons diverses méthodes pour palier aux maux rencontrés 
                                        (digestif, hormonal, articulaire, sommeil, allergies...).
                                        Nous pouvons l'associer au massage, à la fasciathérapie (conseillé pour un meilleur résultat) et la posturologie.
                                        </p>
                                    </div>
                                </div>
                            </div>
                    </div>
                    <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <h3 class="card-title">Reset Emotionnel Auriculothérapie REA</h3>
                                        <p class="details">30 min : 60 €</p>
                                        <img id="oreille" src="./file_assets/rea.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <!-- <p class="heading">Card Hover</p> -->
                                        <p class="texte">
                                        C'est une méthode de l'auriculothérapie visant à supprimer les émotions excessives (post-traumatisme liées à une chute par exemple, 
                                        les phobies, le stress du quotidien...), 
                                        méthode douce (se pratique sans aiguille) dès 6 ans.
                                        </p>
                                    </div>
                                </div>
                            </div>
                    </div>
                </div>
                <div class="ligne">
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <h3 class="card-title">Ventouses</h3>
                                        <p class="details">30 min : 40 €</p>
                                        <img id="oreille" src="./file_assets/ventouse.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <!-- <p class="heading">Card Hover</p> -->
                                        <p class="texte-grand">
                                        Les ventouses sont une aide précieuse pour les maux du quotidien (grippe, rhume, arthrite, dépression, sciatique, anxiété, les douleurs musculaires ...). 
                                        Un massage avec ventouses apportera un effet antalgique puissant, une relaxation musculaire, une amélioration du flux sanguin, une détoxification des organismes et une amélioration de la micro circulation tissulaire.
Les ventouses soulageront l'inflammation, le système lymphatique et les défenses immunitaires seront stimulées (utilisées entre deux séances de chimiothérapie).
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <h3 class="card-title">Massage dos et tensions musculaires</h3>
                                        <p class="details">40 min : 50 €<br>
                                                        50 min : 60 €</p>
                                        <img id="oreille" src="./file_assets/dos.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <!-- <p class="heading">Card Hover</p> -->
                                        <p class="texte">
                                        Le massage permet aux muscles de se détendre, sensation de libération, soulagera les douleurs cervicales, trapèzes, dorsales et lombaires, les jambes plus légères. 
                                        Il procure une réelle détente en libérant les tensions du corps.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <h3 class="card-title">Massage enfant et bébé</h3>
                                        <p class="details-enfant">Séance bébé 15 min : 15 €<br>
                                                            Séance enfant 20 min : 20 €<br>
                                                            Séance enfant 30 min : 30 €<br>
                                                            Séance enfant 40 min : 40 €</p>
                                        <img id="oreille" src="./file_assets/enfant.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <!-- <p class="heading">Card Hover</p> -->
                                        <p class="texte">
                                        Être à l'écoute de votre enfant, de votre bébé, nous entendrons leurs maux, nous passerons le temps nécessaire ensemble pour adapter leur massage, 
                                        des astuces pour la séance bébé et des conseils pour votre enfant.<br>
                                        A chacun son massage (dès 1 mois).<br>
                                        N'hésitez pas à me contacter
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="ligne">
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <h3 class="card-title">Réflexologie plantaire</h3>
                                        <p class="details">30 min : 40 €<br>
                                                            45 min : 55 €</p>
                                        <img id="oreille" src="./file_assets/reflexologie.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <!-- <p class="heading">Card Hover</p> -->
                                        <p class="texte">
                                        La réflexologie plantaire chinoise est destinée à apaiser les tensions et l'équilibre énergétique de notre corps. 
                                        Elle dynamise l'organisme, harmonise les fonctions vitales, libère du stress et les tensions nerveuses, soulage les tensions du dos, améliore la circulation sanguine.
La réflexologie apporte détente et relaxation profonde. Elle active le sytème lymphatique et décontracte les muscles.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <h3 class="card-title">Les massages personnalisés</h3>
                                        <p class="details">1h00 : 70 €<br>
                                                            1h30 : 98 €<br>
                                                            2h00 : 130 €</p>
                                        <img id="oreille" src="./file_assets/massage.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <!-- <p class="heading">Card Hover</p> -->
                                        <p class="texte">
                                        Vous êtes unique, c'est pour cela que je propose un massage adapté à vos besoins, ensemble nous trouverons votre massage, il sera personnalisé, 
                                        nous nous tournerons vers le Tuina, l'ayurvédique, deep tissus, cocooning...
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <h3 class="card-title">Massage ventre Tuina</h3>
                                        <p class="details">30 min : 40 €</p>
                                        <img id="oreille" src="./file_assets/ventre.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <!-- <p class="heading">Card Hover</p> -->
                                        <p class="texte">
                                        C'est un massage issu de la Médecine traditionnelle chinoise. Si vous êtes tendus, vous avez des problèmes digestifs, 
                                        il vous apportera une réelle détente et permettra à l'organisme de retrouver un confort.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="ligne">
                    <div class="container-all">
                        <div class="card-container">
                            <div class="card1">
                                <div class="img-content">
                                    <h3 class="card-title">La Moxibustion</h3>
                                    <p class="details">30 min : 40 €</p>
                                    <img id="oreille" src="./file_assets/moxibustion.png" id="massage" alt="">
                                </div>
                                <div class="content">
                                    <!-- <p class="heading">Card Hover</p> -->
                                    <p class="texte">
                                    La Moxibustion consiste à stimuler avec de la chaleur armoise, des points d'acupuncture et certaines autres parties déterminées du corps humain. C'est une technique thérapeutique utilisée depuis des siècles en Asie et en médecine Chinoise. La moxibustion élimine le stress, 
                                    soulage les douleurs lombaires, refait circuler l'énergie vitale du corps (Qi).
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="container-all">
                        <div class="card-container">
                            <div class="card1">
                                <div class="img-content">
                                    <h3 class="card-title">Massage femme enceinte</h3>
                                    <p class="details">1h00 : 70 €</p>
                                    <img id="oreille" src="./file_assets/femme_enceinte.png" id="massage" alt="">
                                </div>
                                <div class="content">
                                    <!-- <p class="heading">Card Hover</p> -->
                                    <p class="texte">
                                    Venez vous faire chouchouter avec un massage de relaxation adapté à vos besoins (à partir du 4ème mois de grossesse). <br><br>
                                    <strong>Moment de détente pour bébé et vous !</strong>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="container-all">
                        <div class="card-container">
                            <div class="card1">
                                <div class="img-content">
                                    <h3 class="card-title">Massage Japonais du visage dit "Kobido"</h3>
                                    <p class="details">50 min : 60 €</p>
                                    <img id="oreille" src="./file_assets/visage.png" id="massage" alt="">
                                </div>
                                <div class="content">
                                    <!-- <p class="heading">Card Hover</p> -->
                                    <p class="texte">
                                    Ce massage facial intervient sur les méridiens et leurs points énergétiques de façon à libérer les tensions et à participer au rééquilibrage énergétique. Ce massage est exercé sur le cou, le visage et la tête. Il procure une réelle détente, 
                                    atténue les rides d'expression, repulpe le visage et donne de l'éclat à la peau.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ligne">
                    <div class="container-all">
                        <div class="card-container">
                            <div class="card1">
                                <div class="image-content">
                                    <h3 class="card-title">La lampe Wai Qi</h3>
                                    <p class="details">30 min : 45 €<br>
                                                        pack 3 séances : 125 €<br>
                                                        pack 5 séances : 195 €<br>
                                                        pack 10 séances : 350 €</p>
                                    <img id="oreille" src="./file_assets/lampe.png" id="lampe" alt="">
                                </div>
                                <div class="content">
                                    <!-- <p class="heading">Card Hover</p> -->
                                    <p class="texte-grand2">
                                    Apporter une réponse adaptée aux problèmes articulaires, tendineux. Chasse la fatigue, 
                                    renforce l'immunité et le système digestif. Soulage les affections respirations et les diffèrents maux du corps.
                                    La lampe apporte une profonde relaxation, favorise la tonification de l'énergie en apportant l'information de la chaleur qui soutient le bon fonctionnement des diffèrents systèmes (digestif, respiratoire...)
                                    Elle favorise ainsi l'évacuation de l'humidité pathogène du corps qui produit de nombreux troubles de santé. La technologie de la lampe : une chaleur de longueur d'onde infrarouge combinée avec la lithothérapie grâce à une plaque de 33 minéraux.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="container-all">
                    <div class="card-container">
                        <div class="card1">
                            <div class="image-content">
                                <h3 class="card-title">La Pressothérapie</h3>
                                <p class="details">30 min : 40 €<br>
                                                        pack 3 séances : 100 €<br>
                                                        pack 5 séances : 150 €<br>
                                                        pack 10 séances : 380 €</p>
                                <img id="oreille" src="./file_assets/pressotherapie.png" id="pressotherapie" alt="">
                            </div>
                            <div class="content">
                                <!-- <p class="heading">Card Hover</p> -->  
                                <p class="texte">
                                La préssothérapie est une méthode qui améliore la circulation sanguine et lymphatique, favorise l'élimination des toxines, aide le retour veineux , sensation de légèreté dès la première séance. 
                                Pour des résultats durables plusieurs séances sont nécessaires.
                                </p>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
</div>
