<div id="allprestation">
    <h2>Préstations</h2>
        <div id="prestation">
            <div class="wrapper">
                <div class="ligne">
                    <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <p class="details">30 à 45 min : 60 €</p>
                                        <img id="oreille" src="./file_assets/fascia.png" id="massage" alt="">
                                        
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p class="texte">
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                    </div>
                    <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <p class="details">30 à 45 min : 60 €</p>
                                        <img id="oreille" src="./file_assets/auriculotherapie.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p class="texte">
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                    </div>
                    <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <p class="details">30 min : 60 €</p>
                                        <img id="oreille" src="./file_assets/rea.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p class="texte">
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                    </div>
                </div>
                <div class="ligne">
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <p class="details">30 min : 40 €</p>
                                        <img id="oreille" src="./file_assets/ventouse.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p class="texte">
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <p class="details">40 min : 50 €<br>
                                                        50 min : 60 €</p>
                                        <img id="oreille" src="./file_assets/dos.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p class="texte">
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <p class="details-enfant">Séance bébé 15 min : 15 €<br>
                                                            Séance enfant 20 min : 20 €<br>
                                                            Séance enfant 30 min : 30 €<br>
                                                            Séance enfant 40 min : 40 €</p>
                                        <img id="oreille" src="./file_assets/enfant.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p class="texte">
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="ligne">
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <p class="details">30 min : 40 €<br>
                                                            45 min : 55 €</p>
                                        <img id="oreille" src="./file_assets/reflexologie.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p class="texte">
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <p class="details">1h00 : 70 €<br>
                                                            1h30 : 98 €<br>
                                                            2h00 : 130 €</p>
                                        <img id="oreille" src="./file_assets/massage.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p class="texte">
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="container-all">
                            <div class="card-container">
                                <div class="card1">
                                    <div class="img-content">
                                        <p class="details">30 min : 40 €</p>
                                        <img id="oreille" src="./file_assets/ventre.png" id="massage" alt="">
                                    </div>
                                    <div class="content">
                                        <p class="heading">Card Hover</p>
                                        <p class="texte">
                                        Lorem ipsum dolor sit amet, consectetur adipii
                                        voluptas ten mollitia pariatur odit, ab
                                        minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                        necessitatibus dignissimos molestias.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="ligne">
                    <div class="container-all">
                        <div class="card-container">
                            <div class="card1">
                                <div class="img-content">
                                    <p class="details">30 min : 40 €</p>
                                    <img id="oreille" src="./file_assets/moxibustion.png" id="massage" alt="">
                                </div>
                                <div class="content">
                                    <p class="heading">Card Hover</p>
                                    <p class="texte">
                                    Lorem ipsum dolor sit amet, consectetur adipii
                                    voluptas ten mollitia pariatur odit, ab
                                    minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                    necessitatibus dignissimos molestias.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="container-all">
                        <div class="card-container">
                            <div class="card1">
                                <div class="img-content">
                                    <p class="details">1h00 : 70 €</p>
                                    <img id="oreille" src="./file_assets/femme_enceinte.png" id="massage" alt="">
                                </div>
                                <div class="content">
                                    <p class="heading">Card Hover</p>
                                    <p class="texte">
                                    Lorem ipsum dolor sit amet, consectetur adipii
                                    voluptas ten mollitia pariatur odit, ab
                                    minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                    necessitatibus dignissimos molestias.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="container-all">
                        <div class="card-container">
                            <div class="card1">
                                <div class="img-content">
                                    <p class="details">50 min : 60 €</p>
                                    <img id="oreille" src="./file_assets/visage.png" id="massage" alt="">
                                </div>
                                <div class="content">
                                    <p class="heading">Card Hover</p>
                                    <p class="texte">
                                    Lorem ipsum dolor sit amet, consectetur adipii
                                    voluptas ten mollitia pariatur odit, ab
                                    minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                    necessitatibus dignissimos molestias.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ligne">
                    <div class="container-all">
                        <div class="card-container">
                            <div class="card1">
                                <div class="image-content">
                                    <p class="details">30 min : 45 €<br>
                                                        pack 3 séances : 125 €<br>
                                                        pack 5 séances : 195 €<br>
                                                        pack 10 séances : 350 €</p>
                                    <img id="oreille" src="./file_assets/lampe.png" id="lampe" alt="">
                                </div>
                                <div class="content">
                                    <p class="heading">Card Hover</p>
                                    <p class="texte">
                                    Lorem ipsum dolor sit amet, consectetur adipii
                                    voluptas ten mollitia pariatur odit, ab
                                    minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                    necessitatibus dignissimos molestias.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="container-all">
                    <div class="card-container">
                        <div class="card1">
                            <div class="image-content">
                                <p class="details">30 min : 40 €<br>
                                                        pack 3 séances : 100 €<br>
                                                        pack 5 séances : 150 €<br>
                                                        pack 10 séances : 380 €</p>
                                <img id="oreille" src="./file_assets/pressotherapie.png" id="pressotherapie" alt="">
                            </div>
                            <div class="content">
                                <p class="heading">Card Hover</p>
                                <p class="texte">
                                Lorem ipsum dolor sit amet, consectetur adipii
                                voluptas ten mollitia pariatur odit, ab
                                minus ratione adipisci accusamus vel est excepturi laboriosam magnam
                                necessitatibus dignissimos molestias.
                                </p>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
</div>
