<h2> Prestations</h2>
    
    <div class="wrapper">
        <div class="ligne">
            <div class="prestation">
                <div class="image"></div>
                    <div class="product">
                        <span class="product-name">Prestation 1</span>
                        <!-- <span class="product-author">By Hasnain</span> -->
                    </div>
                    <div class="description">
                        <p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do...</p>
                    </div>
                    <div class="price">
                        <div>
                            <span class="price">£25</span>
                            <!-- <span class="now-price">£15</span> -->
                        </div>
                    <button>Plus d'informations</button>
                </div>
            </div>
            <div class="prestation">
                <div class="image"></div>
                    <div class="product">
                        <span class="product-name">Prestation 2</span>
                        <!-- <span class="product-author">By Hasnain</span> -->
                    </div>
                    <div class="description">
                        <p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do...</p>
                    </div>
                    <div class="price">
                        <div>
                            <span class="price">£25</span>
                            <!-- <span class="now-price">£15</span> -->
                        </div>
                    <button>Plus d'informations</button>
                </div>
            </div>
            <div class="prestation">
                <div class="image"></div>
                    <div class="product">
                        <span class="product-name">Prestation 3</span>
                        <!-- <span class="product-author">By Hasnain</span> -->
                    </div>
                    <div class="description">
                        <p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do...</p>
                    </div>
                    <div class="price">
                        <div>
                            <span class="price">£25</span>
                            <!-- <span class="now-price">£15</span> -->
                        </div>
                    <button>Plus d'informations</button>
                </div>
            </div>
            <div class="prestation">
                <div class="image"></div>
                    <div class="product">
                        <span class="product-name">Prestation 4</span>
                        <!-- <span class="product-author">By Hasnain</span> -->
                    </div>
                    <div class="description">
                        <p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do...</p>
                    </div>
                    <div class="price">
                        <div>
                            <span class="price">£25</span>
                            <!-- <span class="now-price">£15</span> -->
                        </div>
                    <button>Plus d'informations</button>
                </div>
            </div>
        </div>
        
    </div>