<div id="allprestations">
    <h2> Prestations</h2>
        <div id="presta">
            <div class="wrapper">
                <div class="ligne">
                    <div class="prestation">
                        <div class="image"></div>
                        <div class="product">
                            <span class="product-name">La fasciathérapie</span>
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <button class="info-button">Plus d'informations</button>
                        </div>
                    </div>
                    <div class="prestation">
                        <div class="image"></div>
                        <div class="product">
                            <span class="product-name">L'auriculothérapie</span>
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <button class="info-button">Plus d'informations</button>
                        </div>
                    </div>
                    <div class="prestation">
                        <div class="image"></div>
                        <div class="product">
                            <span class="product-name">Reset Emotionnel Auriculothérapie REA</span>
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <button class="info-button">Plus d'informations</button>
                        </div>
                    </div>
                    <div class="prestation">
                        <div class="image"></div>
                        <div class="product">
                            <span class="product-name">Ventouses</span>
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <button class="info-button">Plus d'informations</button>
                        </div>
                    </div>
                </div>
                <div class="ligne">
                    <div class="prestation">
                        <div class="image"></div>
                        <div class="product">
                            <span class="product-name">Massage dos et tensions musculaires</span>
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <button class="info-button">Plus d'informations</button>
                        </div>
                    </div>
                    <div class="prestation">
                        <div class="image"></div>
                        <div class="product">
                            <span class="product-name">Massage enfant et bébé</span>
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <button class="info-button">Plus d'informations</button>
                        </div>
                    </div>
                    <div class="prestation">
                        <div class="image"></div>
                        <div class="product">
                            <span class="product-name">Réflexologie plantaire</span>
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <button class="info-button">Plus d'informations</button>
                        </div>
                    </div>
                    <div class="prestation">
                        <div class="image"></div>
                        <div class="product">
                            <span class="product-name">Les massages</span>
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <button class="info-button">Plus d'informations</button>
                        </div>
                    </div>
                </div>
                <div class="ligne">
                    <div class="prestation">
                        <div class="image"></div>
                        <div class="product">
                            <span class="product-name">Massage ventre Tuina</span>
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <button class="info-button">Plus d'informations</button>
                        </div>
                    </div>
                    <div class="prestation">
                        <div class="image"></div>
                        <div class="product">
                            <span class="product-name">La Moxibustion</span>
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <button class="info-button">Plus d'informations</button>
                        </div>
                    </div>
                    <div class="prestation">
                        <div class="image"></div>
                        <div class="product">
                            <span class="product-name">Massage femme enceinte</span>
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <button class="info-button">Plus d'informations</button>
                        </div>
                    </div>
                    <div class="prestation">
                        <div class="image"></div>
                        <div class="product">
                            <span class="product-name">Massage Japonais du visage dit "Kobido"</span>
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <button class="info-button">Plus d'informations</button>
                        </div>
                    </div>
                </div>
                <div class="ligne">
                    <div class="prestation">
                        <div class="image"></div>
                        <div class="product">
                            <span class="product-name">La lampe Wai Qi</span>
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <button class="info-button">Plus d'informations</button>
                        </div>
                    </div>
                    <div class="prestation">
                        <div class="image"></div>
                        <div class="product">
                            <span class="product-name">La Pressothérapie</span>
                        </div>
                        <div class="description">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        </div>
                        <div class="price">
                            <div>
                                <!-- <span class="price">50 euros</span> -->
                            </div>
                            <button class="info-button">Plus d'informations</button>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>