<h2> Prestations</h2>
    
    <div id="all">
        <div class="wrapper">
            <div class="ligne">
                <div class="prestation">
                    <div class="image"></div>
                    <div class="product">
                        <span class="product-name">Prestation 1</span>
                    </div>
                    <div class="description">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    </div>
                    <div class="price">
                        <div>
                            <!-- <span class="price">50 euros</span> -->
                        </div>
                        <button class="info-button">Plus d'informations</button>
                    </div>
                </div>
                <div class="prestation">
                    <div class="image"></div>
                    <div class="product">
                        <span class="product-name">Prestation 2</span>
                    </div>
                    <div class="description">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    </div>
                    <div class="price">
                        <div>
                            <!-- <span class="price">50 euros</span> -->
                        </div>
                        <button class="info-button">Plus d'informations</button>
                    </div>
                </div>
                <div class="prestation">
                    <div class="image"></div>
                    <div class="product">
                        <span class="product-name">Prestation 3</span>
                    </div>
                    <div class="description">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    </div>
                    <div class="price">
                        <div>
                            <!-- <span class="price">50 euros</span> -->
                        </div>
                        <button class="info-button">Plus d'informations</button>
                    </div>
                </div>
                <div class="prestation">
                    <div class="image"></div>
                    <div class="product">
                        <span class="product-name">Prestation 4</span>
                    </div>
                    <div class="description">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    </div>
                    <div class="price">
                        <div>
                            <!-- <span class="price">50 euros</span> -->
                        </div>
                        <button class="info-button">Plus d'informations</button>
                    </div>
                </div>
            </div>
            <div class="ligne">
                <div class="prestation">
                    <div class="image"></div>
                    <div class="product">
                        <span class="product-name">Prestation 5</span>
                    </div>
                    <div class="description">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    </div>
                    <div class="price">
                        <div>
                            <!-- <span class="price">50 euros</span> -->
                        </div>
                        <button class="info-button">Plus d'informations</button>
                    </div>
                </div>
                <div class="prestation">
                    <div class="image"></div>
                    <div class="product">
                        <span class="product-name">Prestation 6</span>
                    </div>
                    <div class="description">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    </div>
                    <div class="price">
                        <div>
                            <!-- <span class="price">50 euros</span> -->
                        </div>
                        <button class="info-button">Plus d'informations</button>
                    </div>
                </div>
                <div class="prestation">
                    <div class="image"></div>
                    <div class="product">
                        <span class="product-name">Prestation 7</span>
                    </div>
                    <div class="description">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    </div>
                    <div class="price">
                        <div>
                            <!-- <span class="price">50 euros</span> -->
                        </div>
                        <button class="info-button">Plus d'informations</button>
                    </div>
                </div>
                <div class="prestation">
                    <div class="image"></div>
                    <div class="product">
                        <span class="product-name">Prestation 8</span>
                    </div>
                    <div class="description">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    </div>
                    <div class="price">
                        <div>
                            <!-- <span class="price">50 euros</span> -->
                        </div>
                        <button class="info-button">Plus d'informations</button>
                    </div>
                </div>
            </div>
            <div class="ligne">
                <div class="prestation">
                    <div class="image"></div>
                    <div class="product">
                        <span class="product-name">Prestation 9</span>
                    </div>
                    <div class="description">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    </div>
                    <div class="price">
                        <div>
                            <!-- <span class="price">50 euros</span> -->
                        </div>
                        <button class="info-button">Plus d'informations</button>
                    </div>
                </div>
                <div class="prestation">
                    <div class="image"></div>
                    <div class="product">
                        <span class="product-name">Prestation 10</span>
                    </div>
                    <div class="description">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    </div>
                    <div class="price">
                        <div>
                            <!-- <span class="price">50 euros</span> -->
                        </div>
                        <button class="info-button">Plus d'informations</button>
                    </div>
                </div>
                <div class="prestation">
                    <div class="image"></div>
                    <div class="product">
                        <span class="product-name">Prestation 11</span>
                    </div>
                    <div class="description">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    </div>
                    <div class="price">
                        <div>
                            <!-- <span class="price">50 euros</span> -->
                        </div>
                        <button class="info-button">Plus d'informations</button>
                    </div>
                </div>
                <div class="prestation">
                    <div class="image"></div>
                    <div class="product">
                        <span class="product-name">Prestation 12</span>
                    </div>
                    <div class="description">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    </div>
                    <div class="price">
                        <div>
                            <!-- <span class="price">50 euros</span> -->
                        </div>
                        <button class="info-button">Plus d'informations</button>
                    </div>
                </div>
            </div>
        </div>
</div>