    <div id="center">
        <div class="card"><!-- Fascia -->
            <div class="additional">
                <div class="user-card">
                    <img src="./file_assets/fascia.png" id="fascia" alt="">
                </div>
                <div class="more-info">
                    <h2>La fasciathérapie</h2>
                        <div class="coords">
                            <span>Séance qui aura pour but de soulager le corps de toutes les tensions quotidiennes accumulées, les mauvaises postures, le stress du système digestif occasionnant des "noeuds", nous travaillerons également sur le système nerveux autonome, un rééquilibrage de l'organisme. La personne peut rester habillée (vêtements coton près du corps).</span>
                        </div>
                        <div class="stats">
                            <div>
                                <div class="title">Séance</div>
                                    <div class="value">30 à 45 min : 60 €</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="general">
                            <h2>La fasciathérapie</h2>
                            <p>Séance qui aura pour but de soulager le corps de toutes les tensions quotidiennes accumulées, les mauvaises postures, le stress du système digestif occasionnant des "noeuds", nous travaillerons également sur le système nerveux autonome, un rééquilibrage de l'organisme. La personne peut rester habillée (vêtements coton près du corps).</p>
                            <span class="more">Survolez-moi pour plus d'informations</span>
                        </div>
                </div>
            </div>
        </div>
        <div class="card"><!-- L'auriculothérapie -->
            <div class="additional">
                <div class="user-card">
                    <img id="oreille" src="./file_assets/oreille.png" id="oreille" alt="">
                </div>
                <div class="more-info">
                    <h2>L'auriculothérapie</h2>
                        <div class="coords">
                            <span>Et si on s'occupait de vos oreilles ! L'oreille est le reflet de notre état général, le saviez-vous ? Au même titre que la réflexologie, l'auriculothérapie vous rééquilibrera, une méthode douce (sans aiguille) où nous utiliserons diverses méthodes pour palier aux maux rencontrés (digestif, hormonal, articulaire, sommeil, allergies...).</br>
                            Nous pouvons l'associer au massage, à la fasciathérapie (conseillé pour un meilleur résultat) et la posturologie.</span>
                        </div>
                        <div class="stats">
                            <div>
                                <div class="title">Séance</div>
                                    <div class="value">30 à 45 min : 60 €</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="general">
                            <h2>L'auriculothérapie</h2>
                            <p>Et si on s'occupait de vos oreilles ! L'oreille est le reflet de notre état général, le saviez-vous ? Au même titre que la réflexologie, l'auriculothérapie vous rééquilibrera, une méthode douce (sans aiguille) où nous utiliserons diverses méthodes pour palier aux maux rencontrés (digestif, hormonal, articulaire, sommeil, allergies...).</br>
                            Nous pouvons l'associer au massage, à la fasciathérapie (conseillé pour un meilleur résultat) et la posturologie.</p>
                            <span class="more">Survolez-moi pour plus d'informations</span>
                        </div>
                </div>
            </div>
        </div>
        <div class="card"><!-- Reset Emotionnel Auriculothérapie REA -->
            <div class="additional">
                <div class="user-card">
                    <img id="oreille" src="./file_assets/rea.png" id="rea" alt="">
                </div>
                <div class="more-info">
                    <h2>Reset Emotionnel Auriculothérapie REA</h2>
                        <div class="coords">
                            <span>C'est une méthode de l'auriculothérapie visant à supprimer les émotions excessives (post-traumatisme liées à une chute par exemple, les phobies, le stress du quotidien...), méthode douce (se pratique sans aiguille) dès 6 ans.</span>
                        </div>
                        <div class="stats">
                            <div>
                                <div class="title">Séance</div>
                                    <div class="value">30 min : 60 €</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="general">
                            <h2>Reset Emotionnel Auriculothérapie REA</h2>
                            <p>C'est une méthode de l'auriculothérapie visant à supprimer les émotions excessives (post-traumatisme liées à une chute par exemple, les phobies, le stress du quotidien...), méthode douce (se pratique sans aiguille) dès 6 ans.</p>
                            <span class="more">Survolez-moi pour plus d'informations</span>
                        </div>
                </div>
            </div>
        </div>
        <div class="card"><!-- Ventouses -->
            <div class="additional">
                <div class="user-card">
                    <img id="oreille" src="./file_assets/ventouse.png" id="ventouse" alt="">
                </div>
                <div class="more-info">
                    <h2>Ventouses</h2>
                        <div class="coords">
                            <span>Les ventouses sont une aide précieuse pour les maux du quotidien (grippe, rhume, arthrite, dépression, sciatique, anxiété, les douleurs musculaires ...).
                                Un massage avec ventouses apportera un effet antalgique puissant, une relaxation musculaire, une amélioration du flux sanguin, une détoxification des organismes et une amélioration de la micro
                                circulation tissulaire. </br>
                                Les ventouses soulageront l'inflammation, le système lymphatique et les défenses immunitaires seront stimulées (utilisées entre deux séances de chimiothérapie).</span>
                        </div>
                        <div class="stats">
                            <div>
                                <div class="title">Séance</div>
                                    <div class="value">30 min : 40 €</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="general">
                            <h2>Ventouses</h2>
                            <p>Les ventouses sont une aide précieuse pour les maux du quotidien (grippe, rhume, arthrite, dépression, sciatique, anxiété, les douleurs musculaires ...).
                                Un massage avec ventouses apportera un effet antalgique puissant, une relaxation musculaire, une amélioration du flux sanguin, une détoxification des organismes et une amélioration de la micro
                                circulation tissulaire. </br>
                                Les ventouses soulageront l'inflammation, le système lymphatique et les défenses immunitaires seront stimulées (utilisées entre deux séances de chimiothérapie).</p>
                            <span class="more">Survolez-moi pour plus d'informations</span>
                        </div>
                </div>
            </div>
        </div>
    </div>
